version: '3.3'
services:
  django_backend:
    container_name: django-backend
    build: 
      context: .
      dockerfile: DockerFile
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    volumes:
      - ./challenge:/challenge
    restart: always
    env_file:
      - .env
    depends_on:
      - pgadmin


  db:
    container_name: ${POSTGRES_HOST}
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    # se expuso el puerto para pruebas
    # ports:
    #   - "5432:5432"


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "${PGADMIN_LISTEN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db